### ISSUE TITLE
Can the official open source part of ‘vex_vision_utility-win’?

### ISSUE THREAD

**Issue by 3038922** [jpearman/viq_vision#1]
I am making a simulator based on pros and lvgl.
https://github.com/3038922/pros-lvgl-sim
https://github.com/3038922/ncrapi_lvgl_sim_kernel

I want to be able to get real sensor information on a computer, not a bunch of random numbers.
Just give me the .h .hpp file and the .lib.like pros.
It’s best to have documents.

**Comment by jpearman** [comment]
The vision utility that VEX provides with VEXcode and allows the PROS team to redistribute is not written in C++, so there are no .h .hpp or .lib files.  The app is written using web technologies such as typescript and is closed source.

**Comment by 3038922** [comment]
thank you
